[package]
name = "rbb"
version = "0.1.0"
authors = ["mokou <mokou@posteo.de>"]
edition = "2018"

[dependencies]
tide = "0.14.0"
async-std = { version = "1.7.0", features = ["attributes"] }
driftwood = "0.0.4"
askama_tide = "0.11.2"
askama = "0.10.3"
comrak = "0.8.2"
