[package]
name = "tidal"
version = "0.1.0"
authors = ["mokou <mokou@posteo.de>"]
edition = "2018"

[dependencies]
tide = "0.13.0"
async-std = { version = "1.6.3", features = ["attributes"] }
driftwood = "0.0.3"
askama_tide = "0.11.0"
askama = "0.10.3"
comrak = "0.8.2"
